image: gcc

variables:
  BIN_NAME: main.out

stages:
  - check_style
  - build
  - test_bin
  - test_mem

check_style:
  stage: check_style
  script:
    - ./linters/run.sh

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - ${BIN_NAME}