on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: make check
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - run: make build
        with:
          path: main.out
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: make test
  memtest:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - run: make memtest